import type { Language, TranslationKey } from './i18n';
import { translations } from './i18n';

const titles = {
    offCenter: 'offCenter',
    time: 'time', distance: 'distance', radius: 'radius', travelled: 'travelled', meeting: 'meeting',
    state: 'state', quasi: 'quasi', orbit: 'orbit', shape: 'shape', speed: 'speed', measurement: 'measurement',
    zoom: 'zoom', autoZoom: 'autoZoom', trails: 'trails', outline: 'outline', center: 'center', vectors: 'vectors',
    physics: 'details', accuracy: 'radiusError', controls: 'pursuit', camera: 'zoom',
} satisfies Record<string, TranslationKey>;
export type HelpTopic = keyof typeof titles;

export const explanations: Record<Language, Record<HelpTopic, string>> = {
    en: {
        offCenter: 'Off by default: wheel, pinch and slider zoom stay anchored to the original center, and dragging or arrow keys cannot pan. Enable this option to zoom at the pointer and move the camera freely. Turning it off recenters the view while preserving the zoom level and Auto zoom setting. It never resets physics. Center still recenters and restores Auto zoom without changing this preference.',
        time: 'Time advanced by the physics engine, in seconds. It stops while paused. A fixed 1/240 s physics tick keeps the result independent of screen refresh rate. Returning from a background tab does not fast-forward the hidden time.',
        distance: 'The average distance between each drone and the next drone it pursues. In a perfectly regular polygon every neighbor distance is equal. This value shrinks as the drones converge; it is not the distance travelled.',
        radius: 'The average distance from a drone to the original center, measured in meters. The center stays fixed even when you pan the camera. Auto zoom changes pixels per meter, so the polygon may look the same size while this physical radius decreases.',
        travelled: 'The average path length travelled by one drone, not the sum for the whole group. The engine adds the lengths of numerical displacements. It should be close to speed × elapsed time at constant speed, or ∫v dt when speed changes. Circle mode uses exact arc lengths.',
        meeting: 'Predicted total simulation time at which the drones meet at the center, not a countdown. For a finite regular polygon: T = R₀ / [v sin(π/N)]. Changing speed updates the remaining-time prediction without resetting elapsed time. The ideal circle has zero inward speed, so its meeting time is ∞.',
        state: 'Converging means finite pursuit toward the center. Quasi-orbit means the inward component is small, but convergence still happens. Stable orbit applies only to the ideal Circle mode. Paused preserves positions and time. Complete means the finite run reached its small convergence tolerance.',
        quasi: 'A quasi-orbit looks almost circular because most velocity is tangential. Here the label appears when sin(π/N) < 0.05: less than 5% of speed points inward. For every finite N this fraction is still positive, so the drones eventually meet. It is not a permanent orbit. Zoom toward a drone with the wheel and drag the canvas to inspect its motion.',
        orbit: 'Circle mode represents the ideal mathematical limit, not a polygon with many drones. Radial speed is zero; tangential speed equals the configured speed. The 64 visible samples rotate at constant radius with angular speed v/R. They never meet, so the meeting time is ∞.',
        shape: 'N is both the number of sides and the number of drones. Drone i pursues drone i+1 clockwise; the last pursues the first. The last slider position is the separate ideal Circle mode. Changing shape resets the run.\n\nLong names use a consistent Greek-prefix convention: dihecta (200) + pentaconta (50) + hexa (6) + gon gives Dihectapentacontahexagon (256). The localized compounds are one naming convention; alternative spellings exist.',
        speed: 'All drones use the same speed in meters per second. Only direction changes during pursuit. Moving this slider applies the new speed immediately without moving or resetting the drones. Higher speed shortens the remaining meeting time. Extremely small, fast setups can run slower than real time to keep the calculation stable.',
        measurement: 'Side length s is the distance between neighboring initial vertices. Perimeter P is the sum of all sides: P = N × s. The starting radius is R₀ = s / [2 sin(π/N)]. Changing measurement converts the value to preserve size, but resets the run. Circle mode uses circumference and R = P/(2π). Changing the length also resets positions and trails.',
        zoom: 'With Off-center navigation disabled, all zoom stays at the original center and panning is locked. Enable it for pointer-anchored zoom and panning. Zoom changes only pixels per meter. The slider zooms around the current camera center. Wheel zoom stays anchored under the pointer; drag to move the camera away from the center. Manual navigation disables Auto zoom. Enable Auto zoom, double-click the canvas, or press Home with the canvas focused to return to the centered view.',
        autoZoom: 'The camera follows the live drone radius, leaving about 10% of the shorter viewport dimension as padding on each side. It ignores old trails and the original outline, so those may be cropped. The radius-based camera avoids pulsing as the polygon rotates. Enabling this option recenters the camera. At completion the camera stops zooming.',
        trails: 'Trails show past drone positions. Each drone stores at most 1,024 points, sampled at up to 30 times per simulated second. Old points are replaced during long runs. Turning trails off stops recording; turning them back on resumes recording. Stop clears all trails.',
        outline: 'The dashed outline shows the initial shape; the solid outline connects the current drones to their next targets. They are visual guides, not forces or walls. Auto zoom may crop the initial outline as the drones move inward.',
        center: 'The small cross marks the geometric center of the original polygon. Finite regular pursuit converges here. It stays at the same world coordinates when the camera pans or zooms; it may then be outside the viewport.',
        vectors: 'Arrows show instantaneous velocity direction toward the next drone. Their display lengths are limited for readability, so they are not a precise speed scale. In ideal Circle mode arrows are tangent to the circle rather than pointed toward the next display sample.',
        physics: 'Each drone continuously pursues the next. Every integration stage reads the same snapshot of all positions before updating any drone, using fourth-order Runge–Kutta with fixed ticks and smaller substeps near convergence.\n\nFor a regular N-gon: inward speed = v sin(π/N), tangential speed = v cos(π/N), and R(t) = R₀ − v sin(π/N)t at constant speed. These formulas check the numerical simulation; they do not generate its paths. Finite runs stop at a small radius tolerance to avoid division by zero.',
        accuracy: 'Radius error = |simulated radius − expected radius| / R₀ × 100%. Dividing by the initial radius keeps this defined near the meeting point. Expected radius uses accumulated ∫v dt if speed changes.\n\nPath error compares numerical path length with ∫v dt. Tiny differences are expected because curved paths are approximated by short displacements. Radius and neighbor-distance spreads measure how closely the drones retain symmetry. Smaller values mean better agreement; rounding to zero does not mean an exact calculation.',
        controls: 'Play starts or resumes. Pause freezes physics and elapsed time. Stop fully resets positions, time, travelled distance and trails. Play after completion starts a fresh run. Shape or size changes also reset; speed, language, camera and visual options do not. Switch exchanges the two panes.',
        camera: 'Off-center navigation is off by default: zoom is centered and panning is locked. Enable it for the free-navigation gestures below. Wheel / trackpad scroll: zoom at the pointer. Drag with the left mouse button or one finger: pan. Pinch with two fingers: zoom and pan.\n\nWith the canvas focused, use +/− to zoom and arrow keys to move the view. Double-click, press Home, or enable Auto zoom to recenter and fit the drones. These actions never alter the physics or reset the run.',
    },
    ru: {
        offCenter: 'По умолчанию выключено: колесо, жест двумя пальцами и ползунок меняют масштаб вокруг исходного центра; перетаскивание и стрелки не сдвигают камеру. Включите для масштаба у указателя и свободного перемещения. Выключение возвращает центр, сохраняя масштаб и настройку автомасштаба. Физика не сбрасывается. Кнопка «В центр» возвращает центр и автомасштаб, не меняя эту настройку.',
        time: 'Время, рассчитанное физическим движком, в секундах. На паузе оно не идёт. Фиксированный шаг 1/240 с делает результат независимым от частоты экрана. После возвращения из фоновой вкладки скрытое время не догоняется.',
        distance: 'Среднее расстояние от каждого дрона до следующего, которого он преследует. В правильном многоугольнике все такие расстояния равны. При сближении значение уменьшается. Это не пройденный путь.',
        radius: 'Среднее расстояние от дронов до исходного центра, в метрах. Центр не перемещается при сдвиге камеры. Автомасштаб меняет число пикселей на метр: фигура может выглядеть одинаково большой, хотя физический радиус уменьшается.',
        travelled: 'Средний путь одного дрона, а не сумма путей всей группы. Движок складывает длины численных перемещений. При постоянной скорости результат близок к скорости × времени, при изменяемой — к ∫v dt. Для окружности используется точная длина дуги.',
        meeting: 'Расчётное время встречи от начала симуляции, а не обратный отсчёт. Для конечного правильного многоугольника T = R₀ / [v sin(π/N)]. Изменение скорости обновляет прогноз оставшегося времени без сброса прошедшего. У идеальной окружности скорость внутрь равна нулю, поэтому время встречи — ∞.',
        state: 'Сближение — конечная погоня к центру. Квазиорбита — малая радиальная составляющая, но встреча всё равно произойдёт. Устойчивая орбита бывает только в идеальном режиме окружности. Пауза сохраняет координаты и время. Завершено означает, что достигнут малый допуск сходимости.',
        quasi: 'Квазиорбита выглядит почти круговой, потому что большая часть скорости направлена по касательной. Здесь название появляется при sin(π/N) < 0,05: внутрь направлено меньше 5% скорости. При любом конечном N эта доля положительна, и дроны в итоге встретятся. Это не вечная орбита. Приблизьте дрон колесом мыши и сдвиньте камеру перетаскиванием, чтобы рассмотреть движение.',
        orbit: 'Окружность представляет идеальный математический предел, а не многоугольник с большим числом дронов. Радиальная скорость равна нулю, касательная — заданной скорости. 64 видимые точки вращаются при постоянном радиусе с угловой скоростью v/R. Они не встретятся; время встречи — ∞.',
        shape: 'N — одновременно число сторон и дронов. Дрон i преследует дрон i+1 по часовой стрелке; последний преследует первого. Последнее положение ползунка — отдельный идеальный режим окружности. Изменение фигуры сбрасывает прогон.\n\nДлинные названия составлены из греческих приставок: дигекта (200) + пентаконта (50) + гекса (6) + гон = Дигектапентаконтагексагон (256). Это единая схема локализованных названий; возможны другие написания.',
        speed: 'Все дроны имеют одинаковую скорость в метрах в секунду. При преследовании меняется направление. Ползунок сразу применяет новую скорость без перемещения и сброса дронов. Большая скорость сокращает время до встречи. Очень маленькие и быстрые конфигурации могут рассчитываться медленнее реального времени ради устойчивости.',
        measurement: 'Длина стороны s — расстояние между соседними исходными вершинами. Периметр P — сумма сторон: P = N × s. Начальный радиус R₀ = s / [2 sin(π/N)]. Смена способа измерения сохраняет размер через пересчёт значения, но сбрасывает прогон. Для окружности задаётся её длина и R = P/(2π). Изменение длины также сбрасывает координаты и следы.',
        zoom: 'При выключенной свободной камере масштаб привязан к исходному центру, сдвиг заблокирован. Включите её для масштаба у указателя и перемещения. Масштаб меняет только число пикселей на метр. Ползунок приближает относительно текущего центра камеры. Колесо мыши приближает точку под указателем; перетаскивание сдвигает камеру. Ручное управление отключает автомасштаб. Чтобы вернуться к центру, включите автомасштаб, дважды щёлкните по холсту или нажмите Home при фокусе на холсте.',
        autoZoom: 'Камера следит за текущим радиусом дронов и оставляет с каждой стороны около 10% меньшего размера окна. Старые следы и исходный контур не учитываются и могут выходить за кадр. Использование радиуса предотвращает пульсацию при вращении. Включение настройки возвращает камеру к центру. При завершении приближение останавливается.',
        trails: 'Следы показывают прошлые положения дронов. Для каждого хранится до 1 024 точек с частотой до 30 точек за секунду симуляции. В длинных прогонах старые точки заменяются. Отключение следов останавливает запись, включение возобновляет. Стоп очищает все следы.',
        outline: 'Пунктирный контур показывает исходную фигуру, сплошной соединяет текущие положения дронов с их целями. Это ориентиры, а не силы или стены. По мере сближения автомасштаб может обрезать исходный контур.',
        center: 'Крестик отмечает геометрический центр исходного многоугольника. Здесь сходится конечная правильная конфигурация. При сдвиге и масштабировании камеры координаты центра не меняются; он может оказаться за кадром.',
        vectors: 'Стрелки показывают мгновенное направление скорости к следующему дрону. Их длина ограничена для читаемости и не служит точной шкалой скорости. В режиме окружности стрелки направлены по касательной, а не к следующей отображаемой точке.',
        physics: 'Каждый дрон непрерывно преследует следующего. Все скорости на стадии интегрирования вычисляются по одному снимку координат. Затем положения обновляются методом Рунге — Кутты четвёртого порядка с фиксированными шагами и более мелкими подшагами около встречи.\n\nДля правильного N-угольника: скорость внутрь = v sin(π/N), касательная скорость = v cos(π/N), R(t) = R₀ − v sin(π/N)t при постоянной скорости. Формулы проверяют численную симуляцию, а не создают траектории. Конечный прогон останавливается при малом радиусе, чтобы избежать деления на ноль.',
        accuracy: 'Ошибка радиуса = |численный радиус − ожидаемый радиус| / R₀ × 100%. Деление на начальный радиус сохраняет определённость у точки встречи. При изменении скорости ожидаемый радиус использует накопленное ∫v dt.\n\nОшибка пути сравнивает численный путь с ∫v dt. Небольшие отличия нормальны: кривая приближается короткими перемещениями. Разброс радиусов и соседних расстояний показывает сохранение симметрии. Чем меньше значения, тем лучше согласие; округлённый ноль не означает абсолютно точный расчёт.',
        controls: 'Старт запускает или продолжает симуляцию. Пауза замораживает физику и время. Стоп полностью сбрасывает координаты, время, путь и следы. Старт после завершения начинает новый прогон. Фигура и размер также сбрасывают прогон; скорость, язык, камера и отображение — нет. Смена меняет панели местами.',
        camera: 'Свободная камера по умолчанию выключена: масштаб привязан к центру, сдвиг заблокирован. Включите её для описанных ниже свободных жестов. Колесо мыши или прокрутка тачпада: масштаб у указателя. Перетаскивание левой кнопкой или одним пальцем: сдвиг камеры. Жест двумя пальцами: масштаб и сдвиг.\n\nПри фокусе на холсте используйте +/− для масштаба и стрелки для перемещения. Двойной щелчок, Home или автомасштаб возвращают центр и вписывают дронов в кадр. Это не изменяет физику и не сбрасывает прогон.',
    },
    ro: {
        offCenter: 'Dezactivată implicit: rotița, gestul cu două degete și cursorul modifică scara în jurul centrului inițial; tragerea și săgețile nu deplasează camera. Activează pentru scară la cursor și deplasare liberă. Dezactivarea recentrează fără a schimba scara sau setarea automată. Fizica nu se resetează. Butonul Centrează reface centrul și scara automată fără a schimba această preferință.',
        time: 'Timpul avansat de motorul fizic, în secunde. Se oprește în pauză. Pasul fix de 1/240 s face rezultatul independent de rata de reîmprospătare a ecranului. Revenirea dintr-o filă de fundal nu recuperează timpul petrecut acolo.',
        distance: 'Distanța medie de la fiecare dronă la următoarea, pe care o urmărește. Într-un poligon perfect regulat, toate aceste distanțe sunt egale. Valoarea scade pe măsură ce dronele converg; nu reprezintă drumul parcurs.',
        radius: 'Distanța medie de la drone la centrul inițial, în metri. Centrul rămâne fix când deplasezi camera. Scara automată modifică pixelii pe metru: figura poate părea la fel de mare în timp ce raza fizică scade.',
        travelled: 'Drumul mediu parcurs de o dronă, nu suma pentru întregul grup. Motorul adună lungimile deplasărilor numerice. Rezultatul trebuie să fie apropiat de viteză × timp la viteză constantă, sau de ∫v dt dacă viteza variază. Modul Cerc folosește lungimi exacte de arc.',
        meeting: 'Timpul total estimat al întâlnirii, măsurat de la începutul simulării, nu o numărătoare inversă. Pentru un poligon regulat finit: T = R₀ / [v sin(π/N)]. Schimbarea vitezei actualizează predicția fără a reseta timpul scurs. Cercul ideal are viteză radială zero, deci timpul întâlnirii este ∞.',
        state: 'Convergență înseamnă urmărire finită spre centru. Cvasi-orbită înseamnă o componentă radială mică, dar întâlnirea tot va avea loc. Orbita stabilă se aplică doar modului Cerc ideal. Pauza păstrează pozițiile și timpul. Încheiat înseamnă atingerea toleranței mici de convergență.',
        quasi: 'O cvasi-orbită pare aproape circulară fiindcă cea mai mare parte a vitezei este tangențială. Aici eticheta apare când sin(π/N) < 0,05: sub 5% din viteză este orientată spre centru. Pentru orice N finit, această fracție rămâne pozitivă, deci dronele se întâlnesc în cele din urmă. Nu este o orbită permanentă. Mărește zona unei drone cu rotița și deplasează camera prin tragere pentru a-i observa mișcarea.',
        orbit: 'Modul Cerc reprezintă limita matematică ideală, nu un poligon cu multe drone. Viteza radială este zero, iar cea tangențială este viteza configurată. Cele 64 de puncte vizibile se rotesc la rază constantă cu viteza unghiulară v/R. Nu se întâlnesc, deci timpul întâlnirii este ∞.',
        shape: 'N este atât numărul laturilor, cât și al dronelor. Drona i urmărește drona i+1 în sens orar, iar ultima o urmărește pe prima. Ultima poziție a cursorului selectează modul Cerc ideal separat. Schimbarea figurii resetează simularea.\n\nDenumirile lungi folosesc prefixe grecești: dihecta (200) + pentaconta (50) + hexa (6) + gon formează Dihectapentacontahexagon (256). Aceste forme localizate urmează o convenție consecventă; există și alte variante de scriere.',
        speed: 'Toate dronele au aceeași viteză în metri pe secundă. În timpul urmăririi se schimbă direcția. Cursorul aplică imediat noua viteză fără să mute sau să reseteze dronele. O viteză mai mare scurtează timpul rămas până la întâlnire. Configurațiile foarte mici și rapide pot evolua mai lent decât timpul real pentru a menține stabilitatea calculului.',
        measurement: 'Lungimea laturii s este distanța dintre vârfurile inițiale vecine. Perimetrul P este suma laturilor: P = N × s. Raza inițială este R₀ = s / [2 sin(π/N)]. Schimbarea măsurii convertește valoarea pentru a păstra dimensiunea, dar resetează simularea. Modul Cerc folosește circumferința și R = P/(2π). Schimbarea lungimii resetează și pozițiile și urmele.',
        zoom: 'Cu navigarea liberă dezactivată, scara rămâne la centrul inițial, iar deplasarea este blocată. Activeaz-o pentru scară la cursor și deplasare. Scara modifică doar pixelii pe metru. Cursorul mărește în jurul centrului actual al camerei. Rotița păstrează fix punctul de sub cursor; tragerea deplasează camera. Navigarea manuală dezactivează scara automată. Activează scara automată, fă dublu clic pe canvas sau apasă Home când canvasul are focalizarea pentru a reveni la centru.',
        autoZoom: 'Camera urmărește raza curentă a dronelor, lăsând pe fiecare parte aproximativ 10% din dimensiunea mai mică a ferestrei. Ignoră urmele vechi și conturul inițial, care pot ieși din cadru. Folosirea razei evită pulsațiile în timpul rotației. Activarea opțiunii recentrează camera. La încheiere, mărirea se oprește.',
        trails: 'Urmele arată pozițiile anterioare ale dronelor. Fiecare păstrează cel mult 1 024 de puncte, înregistrate de până la 30 de ori pe secundă simulată. În simulările lungi, punctele vechi sunt înlocuite. Dezactivarea oprește înregistrarea; reactivarea o continuă. Stop șterge toate urmele.',
        outline: 'Conturul punctat arată figura inițială; cel continuu unește dronele curente cu țintele lor. Sunt repere vizuale, nu forțe sau pereți. Pe măsură ce dronele converg, scara automată poate scoate conturul inițial din cadru.',
        center: 'Crucea mică marchează centrul geometric al poligonului inițial. Aici converge configurația regulată finită. Coordonatele centrului nu se schimbă când deplasezi sau mărești camera; centrul poate ajunge în afara ferestrei.',
        vectors: 'Săgețile arată direcția instantanee a vitezei către drona următoare. Lungimile lor sunt limitate pentru lizibilitate și nu reprezintă o scară exactă a vitezei. În modul Cerc, săgețile sunt tangente la cerc, nu orientate către următorul punct afișat.',
        physics: 'Fiecare dronă urmărește continuu următoarea dronă. Fiecare etapă de integrare citește același set de poziții înainte de actualizarea lor, folosind Runge–Kutta de ordinul patru, pași ficși și subpași mai mici aproape de întâlnire.\n\nPentru un poligon regulat cu N laturi: viteza radială = v sin(π/N), cea tangențială = v cos(π/N), iar R(t) = R₀ − v sin(π/N)t la viteză constantă. Formulele verifică simularea numerică; nu îi generează traiectoriile. Simularea finită se oprește la o toleranță mică a razei pentru a evita împărțirea la zero.',
        accuracy: 'Eroarea razei = |raza simulată − raza așteptată| / R₀ × 100%. Împărțirea la raza inițială păstrează valoarea definită aproape de întâlnire. Raza așteptată folosește ∫v dt acumulat dacă viteza se schimbă.\n\nEroarea drumului compară drumul numeric cu ∫v dt. Diferențele mici sunt normale deoarece curbele sunt aproximate prin deplasări scurte. Dispersia razelor și a distanțelor dintre vecini măsoară păstrarea simetriei. Valori mai mici înseamnă acord mai bun; rotunjirea la zero nu înseamnă calcul exact.',
        controls: 'Pornește începe sau continuă simularea. Pauza îngheață fizica și timpul. Stop resetează complet pozițiile, timpul, drumul și urmele. Pornirea după încheiere începe o simulare nouă. Figura și dimensiunea resetează și ele simularea; viteza, limba, camera și afișarea nu. Schimb inversează panourile.',
        camera: 'Navigarea liberă este dezactivată implicit: scara este centrată, iar deplasarea este blocată. Activeaz-o pentru gesturile libere de mai jos. Rotiță / derulare pe touchpad: mărește la poziția cursorului. Tragere cu butonul stâng sau cu un deget: deplasează camera. Gest cu două degete: scară și deplasare.\n\nCând canvasul are focalizarea, folosește +/− pentru scară și săgețile pentru deplasare. Dublu clic, Home sau scara automată recentrează și încadrează dronele. Aceste acțiuni nu schimbă fizica și nu resetează simularea.',
    },
};

export function bindHelp(getLanguage: () => Language) {
    const dialog = document.getElementById('help-dialog') as HTMLDialogElement;
    const heading = document.getElementById('help-title')!;
    const body = document.getElementById('help-body')!;
    const close = document.getElementById('help-close') as HTMLButtonElement;
    const buttons = document.querySelectorAll<HTMLButtonElement>('[data-help]');
    let topic: HelpTopic = 'controls';
    function refresh() {
        const lang = getLanguage();
        for (const button of buttons) {
            const key = button.dataset.help as HelpTopic;
            button.setAttribute('aria-label', `${translations[lang].help}: ${translations[lang][titles[key]]}`);
        }
        const title = translations[lang][titles[topic]];
        const text = explanations[lang][topic].replaceAll('\\n', '\n');
        if (heading.textContent !== title) heading.textContent = title;
        if (body.textContent !== text) body.textContent = text;
        close.textContent = translations[lang].close;
    }
    for (const button of buttons) button.addEventListener('click', event => {
        event.preventDefault();
        topic = button.dataset.help as HelpTopic;
        refresh();
        dialog.showModal();
    });
    close.addEventListener('click', () => dialog.close());
    dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); });
    return refresh;
}


